---
- name: Get Elastic Cluster
  gather_facts: no
  hosts: localhost
  tasks:
  - name: Get Cluster Info
    expedient.elastic.ece_cluster_info:
      host: elastic-admin.expedient.cloud
      port: 12443
      username: api-testing
      password: "{{ece_password}}"
      verify_ssl_cert: True
      deployment_name: 
      deployment_action: get_deployment_id
      check_mode: False
    register: cluster_info
  - name: Show Cluster Settings
    debug:
      var: cluster_info
  - name: Create Agent Policy
    expedient.elastic.elastic_agentpolicy:
      host: "{{cluster_info.deployment_id}}"
      port: 9243
      username: 
      password: 
      verify_ssl_cert: True
      agent_policy_name: Endpoint Security
      agent_policy_desc: Endpoint Security
      agent_policy_action: create
      check_mode: False
    register: agentpolicy_info
  - name: Show Agent Policy Settings
    debug:
      var: agentpolicy_info
  - name: Create Integration Package - System
    expedient.elastic.elastic_endpoint_baseline:
      host: "{{cluster_info.deployment_id}}"
      port: 9243
      username: test1
      password: testing
      verify_ssl_cert: True
      agent_policy_id: "{{agentpolicy_info.agent_policy_object.id}}"
      integration_name: System
      integration_pkg_name: system-1
      integration_pkg_desc: system-1 
      check_mode: False
    register: intpkgpolicy_info
  - name: Show Package Policy Settings
    debug:
      var: intpkgpolicy_info
  - name: Create Integration Packages - Windows
    expedient.elastic.elastic_endpoint_baseline:
      host: "{{cluster_info.deployment_id}}"
      port: 9243
      username: test1
      password: testing
      verify_ssl_cert: True
      agent_policy_id: "{{agentpolicy_info.agent_policy_object.id}}"
      integration_name: Windows
      integration_pkg_name: windows-1
      integration_pkg_desc: windows-1
      check_mode: False
    register: intpkgpolicy_info
  - name: Show Package Policy Settings
    debug:
      var: intpkgpolicy_info
  - name: Create Integration Packages - Windows
    expedient.elastic.elastic_endpoint_baseline:
      host: "{{cluster_info.deployment_id}}"
      port: 9243
      username: test1
      password: testing
      verify_ssl_cert: True
      agent_policy_id: "{{agentpolicy_info.agent_policy_object.id}}"
      integration_name: Linux
      integration_pkg_name: linux-1
      integration_pkg_desc: linux-1
      check_mode: False
    register: intpkgpolicy_info
  - name: Show Package Policy Settings
    debug:
      var: intpkgpolicy_info
  - name: Create Integration Packages - Windows
    expedient.elastic.elastic_endpoint_baseline:
      host: "{{cluster_info.deployment_id}}"
      port: 9243
      username: test1
      password: testing
      verify_ssl_cert: True
      agent_policy_id: "{{agentpolicy_info.agent_policy_object.id}}"
      integration_name: Endpoint Security
      integration_pkg_name: endpoint_security-1
      integration_pkg_desc: endpoint_security-1
      check_mode: False
    register: intpkgpolicy_info
  - name: Show Package Policy Settings
    debug:
      var: intpkgpolicy_info
  - name: Create Integration Packages - Windows
    expedient.elastic.elastic_endpoint_baseline:
      host: "{{cluster_info.deployment_id}}"
      port: 9243
      username: test1
      password: testing
      verify_ssl_cert: True
      agent_policy_id: "{{agentpolicy_info.agent_policy_object.id}}"
      integration_name: Prebuilt Security Detection Rules
      integration_pkg_name: prebuilt_security_detection_rules-1
      integration_pkg_desc: prebuilt_security_detection_rules-1
      check_mode: False
    register: intpkgpolicy_info
  - name: Show Package Policy Settings
    debug:
      var: intpkgpolicy_info
