---
name: Release and Deploy collection
on:
  push:
    tags: '*'

jobs:
  publish:
    runs-on: [self-hosted, prodops]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get collection namespace
        run: |
          echo "namespace=$(grep "namespace: " galaxy.yml | awk '{print $NF }')" >> $GITHUB_ENV

      - name: Get collection name
        run: |
          echo "collection=$(grep "name: " galaxy.yml | awk '{print $NF }')" >> $GITHUB_ENV

      - name: Get current version
        run: |
          echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Append version to galaxy.yml
        run: |
          echo "version: ${{ env.version }}" >> galaxy.yml

      - name: Build Ansible Collection
        run: ansible-galaxy collection build . --force --output-path /tmp

      - name: Publish Ansible Collection
        run: ansible-galaxy collection publish /tmp/${{ env.namespace }}-${{ env.collection }}-${{ env.version }}.tar.gz
